# Change these first
owner: doctorfree # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: asciiville.dev
    url: https://asciiville.dev
  - name: lazyman.dev
    url: https://lazyman.dev
  - name: skunkware.dev
    url: https://skunkware.dev
  - name: musicplayerplus.dev
    url: https://musicplayerplus.dev
  - name: mirrorcommand.dev
    url: https://mirrorcommand.dev
  - name: neoman.dev
    url: https://neoman.dev
  - name: rooncommand.dev
    url: https://rooncommand.dev
  - name: ronrecord.com
    url: https://ronrecord.com
  - name: willowrecord.com
    url: https://willowrecord.com
  - name: archive.ronrecord.com
    url: https://archive.ronrecord.com
  - name: fractals.ronrecord.com
    url: https://fractals.ronrecord.com
  - name: blog.ronrecord.com
    url: https://blog.ronrecord.com
  - name: themes.ronrecord.com
    url: https://doctorfree.github.io/google-chrome-themes

assignees: # Users to assign downtime issues (optional)
  - doctorfree

status-website:
  theme: dark
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: lazyman.dev
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/doctorfree/upptime/master/assets/upptime-icon.svg
  name: Status
  introTitle: "Open source website uptime monitor"
  introMessage: Websites status page using **real-time** data from my [GitHub repository](https://github.com/doctorfree/upptime)
  navbar:
    - title: Repository
      href: https://github.com/$OWNER/$REPO
    - title: Profile
      href: https://github.com/$OWNER

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration